stages:
  - cmake_build
  - bazel_build

before_script:
  - export http_proxy=http://30.57.177.111:3128; export https_proxy=http://30.57.177.111:3128; export ALL_PROXY=30.57.177.111:3128; export PATH=/usr/local/gcc/bin:$PATH

job1:
  stage: cmake_build
  script:
    - mkdir _build; cd _build; cmake -DBUILD_TESTS=1 -DBUILD_INTEGRATION_TESTS=1 -DBUILD_EXAMPLES=1 ..; make -j $(nproc)

job2:
  stage: bazel_build
  script:
    - bazel build //...