name: CPP Build
on: [push, pull_request]
jobs:
  cpp_ubuntu_18_04:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile All Targets
        working-directory: ./cpp
        run: bazel build //...
