name: CPP Build
on: [push, pull_request]
jobs:
  cpp_build:
    name: CPP Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        run: |
          sudo apt-get -qq install npm
          sudo npm install -g @bazel/bazelisk
      - name: Use Bazel
        if: matrix.os != 'windows'
        working-directory: ./cpp
        run: bazel -h
      - name: Compile All Targets
        working-directory: ./cpp
        run: bazel build //...
