name: Java Build
on: [push, pull_request]
jobs:
  java_build:
    name: Java Build Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      working-directory: ./java
      run: mvn -B package --file pom.xml

