# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-20.04, ubuntu-18.04, windows-2016, windows-2019, windows-2022, macos-11, macos-10.15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.1.0
      - name: Use Bazel (Windows only)
        if: matrix.os == 'windows'
        run: ./bazel.exe -h
      - name: Use Bazel
        if: matrix.os != 'windows'
        run: bazel -h
      - name: Compile All Targets
        run: bazel build //...
      - name: Run Unit Tests
        run: bazel test --test_output=errors //src/test/cpp/ut/...